branches:
  only:
    - master
language: perl6
perl6:
  - latest
before_install:
  - sudo apt-get install libgeoip1 geoip-database-contrib
  - sudo ln -s /usr/share/GeoIP/GeoLiteCityv6.dat /usr/share/GeoIP/GeoIPCityv6.dat
